let lessons = [
    {
        "id": 1001,
        "activity": "Football",
        "location": "Dubai",
        "price": "500 AED",
        "image": 'images/football1.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1002,
        "activity": "Cricket",
        "location": "Dubai",
        "price": "650 AED",
        "image": 'images/cricket1.png',
        "numberOfSpaces": 5,
    },

    {
        "id": 1003,
        "activity": "Swimming",
        "location": "Dubai",
        "price": "450 AED",
        "image": 'images/swimming1.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1004,
        "activity": "Rugby",
        "location": "Sharjah",
        "price": "300 AED",
        "image": 'images/rugby1.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1005,
        "activity": "Baseball",
        "location": "Sharjah",
        "price": "500 AED",
        "image": 'images/baseball1.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1006,
        "activity": "Gymnastics",
        "location": "Sharjah",
        "price": "350 AED",
        "image": 'images/gymnastics1.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1007,
        "activity": "Biking",
        "location": "Abu Dhabi",
        "price": "200 AED",
        "image": 'images/biking1.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1008,
        "activity": "Athletics",
        "location": "Abu Dhabi",
        "price": "400 AED",
        "image": 'images/athletics1.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1009,
        "activity": "Chess",
        "location": "Abu Dhabi",
        "price": "300 AED",
        "image": 'images/chess1.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1010,
        "activity": "Badminton",
        "location": "Dubai",
        "price": "450 AED",
        "image": 'images/badminton1.png',
        "numberOfSpaces": 5,
    }
]
