let lessons = [
    {
        "id": 1001,
        "subject": "Music",
        "location": "Dubai",
        "price": "200 AED",
        "image": 'images/music.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1002,
        "subject": "Math",
        "location": "Dubai",
        "price": "400 AED",
        "image": 'images/math.png',
        "numberOfSpaces": 5,
    },

    {
        "id": 1003,
        "subject": "English",
        "location": "Dubai",
        "price": "350 AED",
        "image": 'images/music.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1004,
        "subject": "Music",
        "location": "Sharjah",
        "price": "200 AED",
        "image": 'images/music.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1005,
        "subject": "Math",
        "location": "Sharjah",
        "price": "400 AED",
        "image": 'images/math.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1006,
        "subject": "English",
        "location": "Sharjah",
        "price": "350 AED",
        "image": 'images/music.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1007,
        "subject": "Music",
        "location": "Abu Dhabi",
        "price": "200 AED",
        "image": 'images/music.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1008,
        "subject": "Math",
        "location": "Abu Dhabi",
        "price": "400 AED",
        "image": 'images/math.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1009,
        "subject": "English",
        "location": "Abu Dhabi",
        "price": "300 AED",
        "image": 'images/music.png',
        "numberOfSpaces": 5,
    },
    {
        "id": 1010,
        "subject": "Science",
        "location": "Dubai",
        "price": "450 AED",
        "image": 'images/music.png',
        "numberOfSpaces": 5,
    }
]
